package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Worker;

import greendao.WorkerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workerDaoConfig;

    private final WorkerDao workerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workerDaoConfig = daoConfigMap.get(WorkerDao.class).clone();
        workerDaoConfig.initIdentityScope(type);

        workerDao = new WorkerDao(workerDaoConfig, this);

        registerDao(Worker.class, workerDao);
    }
    
    public void clear() {
        workerDaoConfig.getIdentityScope().clear();
    }

    public WorkerDao getWorkerDao() {
        return workerDao;
    }

}
