package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WORKER.
 */
public class Worker {

    private Long id;
    private String block;
    private String level;
    private String unit;
    private String faceImage;
    private String cardFrontImage;
    private String cardBackImage;
    private Integer uploaded;

    public Worker() {
    }

    public Worker(Long id) {
        this.id = id;
    }

    public Worker(Long id, String block, String level, String unit, String faceImage, String cardFrontImage, String cardBackImage, Integer uploaded) {
        this.id = id;
        this.block = block;
        this.level = level;
        this.unit = unit;
        this.faceImage = faceImage;
        this.cardFrontImage = cardFrontImage;
        this.cardBackImage = cardBackImage;
        this.uploaded = uploaded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBlock() {
        return block;
    }

    public void setBlock(String block) {
        this.block = block;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getFaceImage() {
        return faceImage;
    }

    public void setFaceImage(String faceImage) {
        this.faceImage = faceImage;
    }

    public String getCardFrontImage() {
        return cardFrontImage;
    }

    public void setCardFrontImage(String cardFrontImage) {
        this.cardFrontImage = cardFrontImage;
    }

    public String getCardBackImage() {
        return cardBackImage;
    }

    public void setCardBackImage(String cardBackImage) {
        this.cardBackImage = cardBackImage;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

}
